APP_NAME = "ImageUntangler"
APP_BYLINE = "TCML"
VER_NUMBER = '4.0.0'
WINDOW_NAME = f'{APP_NAME} by {APP_BYLINE} v-{VER_NUMBER}'

BG_COLOR = (204 / 255, 204 / 255, 204 / 255)

CL_INITIAL_HEIGHT = 40
CL_INITIAL_ANGLE = 180

CL_MIN_HEIGHT = 1
CL_MAX_HEIGHT = 100

CL_MIN_ANGLE = 0
CL_MAX_ANGLE = 180

ORDER_OF_CONTROLS = ['Slice Index', "Window", "Level"]

TIMESTAMP_FORMAT = "%d.%m.%Y %H:%M:%S"
